version: '3'

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "15432:5432"
    environment:
      - TZ=UTC
      - POSTGRES_DB=postgres
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
