steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - -c
      - |
        gcloud container clusters get-credentials ${_CLUSTER_NAME} --zone ${_ZONE} --project ${_PROJECT_ID}
        echo "Deploying image ghcr.io/${_REPO_NAME}:latest-api-${_VERSION}"
        ./k8s/app/up-app.sh ${_VERSION}

logs_bucket: "gs://devops-build-log"

substitutions:
  _VERSION: $(body.payload.properties.version)
  _REPO_NAME: "cgtyunerr/devops-task"
  _CLUSTER_NAME: "airline-app"
  _ZONE: "europe-north1-b"
  _PROJECT_ID:  "advance-lacing-459309-b5"
