steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    env:
      - "TAG=${_VERSION}"
    args:
      - -c
      - |
        apt-get update && apt-get install -y gettext
        gcloud container clusters get-credentials ${_CLUSTER_NAME} --zone ${_ZONE} --project ${_PROJECT_ID}
        echo "Deploying image ghcr.io/${_REPO_NAME}:latest-api-${_VERSION}"
        kubectl delete job migration-job --ignore-not-found
        envsubst < k8s/app/job.yaml | kubectl apply -f -
        kubectl wait --for=condition=complete --timeout=180s job/migration-job
        envsubst < k8s/app/deployment.yaml | kubectl apply -f -

logs_bucket: "gs://devops-build-log"

substitutions:
  _VERSION: $(body.payload.properties.version)
  _REPO_NAME: "cgtyunerr/devops-task"
  _CLUSTER_NAME: "airline-app"
  _ZONE: "europe-north1-b"
  _PROJECT_ID:  "advance-lacing-459309-b5"
