steps:
  - name: 'gcr.io/cloud-builders/go'
    args: [ 'install', '.' ]

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    env:
      - 'TAG: ${_VERSION}'
    args:
      - -c
      - |
        echo "Deploying image ghcr.io/${_REPO_NAME}:${_VERSION}..."
        envsubst < app/deployment.yaml | kubectl apply -f -

logs_bucket: "gs://devops-build-log"

substitutions:
  _VERSION: "latest" #default is latest but webhook send version.
  _REPO_NAME: "cgtyunerr/devops-task"
