apiVersion: apps/v1
kind: Deployment
metadata:
  name: airlines-backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox
        command: ['sh', '-c', 'until nc -z -v -w30 $DB__HOST $DB_PORT; do echo "Waiting for PostgreSQL..."; sleep 5; done;']
        envFrom:
        - secretRef:
            name: airlines-backend-env
      - name: run-migrations
        image: ghcr.io/cgtyunerr/devops-task:latest-api-${TAG}
        command: [ "bin/sh" ]
        args: [ "scripts/migrate-all.sh" ]
        envFrom:
          - secretRef:
              name: airlines-backend-env

      containers:
      - name: backend
        image: ghcr.io/cgtyunerr/devops-task:latest-api-${TAG}
        ports:
        - containerPort: 8000
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 60
        resources:
          requests:
           cpu: "250m"
           memory: "500Mi"
          limits:
            cpu: "350m"
            memory: "1Gi"
        envFrom:
        - secretRef:
            name: airlines-backend-env
      imagePullSecrets:
      - name: regcred
