apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox
        command: ['sh', '-c', 'until nc -z -v -w30 $DB__HOST $DB_PORT; do echo "Waiting for PostgreSQL..."; sleep 5; done;']
        envFrom:
        - secretRef:
            name: airlines-backend-env
      containers:
      - name: run-migration-up
        image: ghcr.io/cgtyunerr/devops-task:latest-api-${TAG}
        command: ["bin/bash", "-c", "./deployment-scripts/migrate-all.sh"]
        envFrom:
        - secretRef:
            name: airlines-backend-env
      imagePullSecrets:
      - name: regcred
