---
name: Main workflow

on:
  push:

concurrency:
  group: main-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    if: github.ref == 'refs/heads/main'
    needs: test
    uses: ./.github/workflows/release.yml
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
