---
name: Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    environment: test
    env:
      DB__PORT: 5432
      DB__PASS: dbpass
      DB__USER: dbuser
      DB__NAME: postgres
      DB__HOST: localhost
      LOG_LEVEL: info
      JWT_SECRET: "secret"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Start docker-compose
        run: docker compose -f docker-compose.test.yml up -d

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install poetry
        run: pip install poetry

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Check lint
        run: SKIP=no-commit-to-branch make lint

      - name: Install library
        run: |
          poetry lock
          poetry install

      - name: Create test environment
        run: |
          scripts/test-setup.sh

      - name: Project tests
        run: poetry run python -m pytest -lv tests

      - name: User Module Tests
        run: |
          scripts/test.sh app/modules/user
